one <- read.table("./1.txt",header=T,sep=";",skip=66636,nrows=2880)
one1 <- read.table("./1.txt",header=T,sep=";",nrows=2)
names(one1)->names(one)
dt<-as.POSIXlt(paste(as.Date(one$Date, format="%d/%m/%Y"), one$Time, sep=" "))
png(file="plot4.png",width=480,height=480)
par(mfcol=c(2,2))
plot(dt,one$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(dt,one$Sub_metering_1,type="l",xlab="",ylab="Energy Sub Metering")
lines(dt,one$Sub_metering_2,type="l",col="red")
lines(dt,one$Sub_metering_3,type="l",col="blue")
legend("topright",pch=95,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(dt,one$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(dt,one$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()