one <- read.table("./1.txt",header=T,sep=";",skip=66636,nrows=2880)
one1 <- read.table("./1.txt",header=T,sep=";",nrows=2)
names(one1)->names(one)
dt<-as.POSIXlt(paste(as.Date(one$Date, format="%d/%m/%Y"), one$Time, sep=" "))
png(file="plot3.png",width=480,height=480)
plot(dt,one$Sub_metering_1,type="l",xlab="",ylab="Energy Sub Metering")
lines(dt,one$Sub_metering_2,type="l",col="red")
lines(dt,one$Sub_metering_3,type="l",col="blue")
legend("topright",pch=95,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()